project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("registros/", include('records.urls')),
    path("", lambda request: redirect("registros/login/")),
]

records/urls.py
from django.urls import path
from records import views

urlpatterns = [
    # login/logout
    path("login/", views.login_view, name='login_view'),
    path("logout/", views.logout_view, name='logout_view'),
    
    # employeers
    path("funcionario/", views.register_employee, name='register_employee'),
    
    # key
    path('chave/', views.register_key, name='register_key'),
    
    # EPI
    path('epi/', views.register_epi, name='register_epi'),
    
    # alert
    path('success/', views.success_page, name='success_page'),
]

records/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Sector(models.Model):
    name = models.CharField(max_length=255)
    phone = models.PositiveIntegerField()
    
    def __str__(self):
        return self.name
    
    
class Enterprise(models.Model):
    name = models.CharField(max_length=255)
    
    def __str__(self):
        return self.name


class RegisterEmployee(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    credential = models.PositiveIntegerField()
    enterprise = models.ForeignKey(Enterprise, on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.firstname} {self.lastname}'
    
    
class RegisterKey(models.Model):
    name = models.CharField(max_length=255)
    number = models.PositiveIntegerField()
    amount = models.PositiveIntegerField(default=1)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'Chave: {self.name} | Número: {self.number}'
    
    
class RegisterEPI(models.Model):
    name = models.CharField(max_length=255)
    number = models.PositiveIntegerField()
    amount = models.PositiveIntegerField(default=1)
    description = models.TextField(max_length=500, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    create_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.name}'
    
    
    

records/forms.py
from django.forms import ModelForm
from . import models

class EmployeeForm(ModelForm):
    class Meta:
        model = models.RegisterEmployee
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['firstname'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Primeiro nome'}
        )
        
        self.fields['lastname'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Sobrenome'}
        )
        
        self.fields['credential'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Credencial'}
        )
        
        self.fields['enterprise'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Empresa'}
        )
        
        self.fields['sector'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Setor'}
        )
        
        self.fields['user'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Portaria'}
        )
        
        
class KeyForm(ModelForm):
    class Meta:
        model = models.RegisterKey
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Nome da chave'}
        )
        
        self.fields['number'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Número'}
        )
        
        self.fields['amount'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Quantidade de cópias'}
        )
        
        self.fields['user'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Portaria'}
        )
        
        
class EPIForm(ModelForm):
    class Meta:
        model = models.RegisterEPI
        fields = '__all__'
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Nome da chave'}
        )
        
        self.fields['number'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Número'}
        )
        
        self.fields['amount'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Quantidade de cópias'}
        )
        
        self.fields['description'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Descrição'}
        )
        
        self.fields['user'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Portaria'}
        )
        
    
        
        
        

records/views.py
from django.shortcuts import render, redirect
from records import forms, models
from django.contrib import messages

# Create your views here.
def login_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('register_employee')
    
        return render(request, 'pages/login/login.html')


def logout_view(request):
    return render(request, 'pages/login/logout.html')


def register_employee(request):
    if request.method == 'POST':
        form = forms.EmployeeForm(request.POST)
        sector = request.POST.get('sector_name')
        phone = request.POST.get('sector_phone')
        enterprise = request.POST.get('enterprise')
        
        if form.is_valid():
            register = form.save(commit=False)
            register.user = request.user
            register.save()
            
        elif enterprise:
            enterprise_nome = models.Enterprise(name=enterprise)
            enterprise_nome.save()
                
        elif sector and phone:
            sector_data = models.Sector(name=sector, phone=phone)
            sector_data.save()
                
        return redirect('register_employee')
    form = forms.EmployeeForm()
    context = {'form': form}
    return render(request, 'pages/employee/employee_create.html', context=context)

def register_key(request):
    if request.method == 'POST':
        form = forms.KeyForm(request.POST)
        if form.is_valid():
            register = form.save(commit=False)
            register.user = request.user
            register.save()
            
        return redirect('register_key')
    
    form = forms.KeyForm()
    context = {'form': form}
    return render(request, 'pages/key/key_create.html', context=context)


def register_epi(request):
    if request.method == 'POST':
        form = forms.EPIForm(request.POST)
        if form.is_valid():
            register = form.save(commit=False)
            register.user = request.user
            register.save()
            messages.success(request, 'Epi cadastrado com sucesso!')
            
        return redirect('register_epi')
    
    form = forms.EPIForm()
    context = {'form': form}
    return render(request, 'pages/epi/epi_create.html', context=context)


def success_page(request):
    return render(request, 'pages/alert/success.html')
            

records/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include "partials/_header.html" %}
        <main class='d-flex justify-content-center align-items-center vh-100'>
            {% block content %}{% endblock content %}
        </main>
    {% include "partials/_footer.html" %}
    <script src="{% static "js/script.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/js/all.min.js" integrity="sha512-b+nQTCdtTBIRIbraqNEwsjB6UvL3UEMkXnhzd8awtCYh0Kcsjl9uEgwVFVbhoj3uu1DO1ZMacNvLoyJJiNfcvg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

records/templates/pages/alert/success.html
{% extends "base.html" %}
{% block title %}Sucesso!{% endblock title %}

{% block content %}
    <div class="alert alert-success" role="alert">
        Cadastrado com sucesso!
    </div>
{% endblock content %}

records/templates/pages/employee/employee_create.html
{% extends "base.html" %}
{% block title %}Employee{% endblock title %}

{% block content %}

<form action="{% url "register_employee" %}" method="post">{% csrf_token %}

<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-circle-user"></i></span>
    <div class="form-floating">
      {{form.firstname}}
      <label for="id_firstname">Primeiro nome</label>
    </div>
</div>
    
<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-regular fa-circle-user"></i></span>
    <div class="form-floating">
      {{form.lastname}}
      <label for="id_lastname">Sobrenome</label>
    </div>
</div>

<div class="input-group mb-3">
  <span class="input-group-text"><i class="fa-solid fa-address-card"></i></span>
  <div class="form-floating">
    {{form.credential}}
    <label for="id_credential">Credencial</label>
  </div>
</div>

<div class="input-group mb-3">
  <span class="input-group-text"><i class="fa-solid fa-city"></i></span>
  <div class="form-floating">
    {{form.enterprise}}
    <label for="id_enterprise">Empresa</label>
  </div>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#empresaModal">
    Cadastrar
  </button>
</div>

<div class="input-group mb-3">
  <span class="input-group-text"><i class="fa-solid fa-building-circle-check"></i></span>
  <div class="form-floating">
    {{form.sector}}
    <label for="id_sector">Setor</label>
  </div>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#setorModal">
    Cadastrar
  </button>
</div>

<div class="mb-3">
  <button type="submit" class="btn btn-outline-primary btn-lg w-100">Registrar <i class="fa-solid fa-check"></i></button>
</div>

</form>


<!-- Modal Empresa -->
<div class="modal fade" id="empresaModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="empresaModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="empresaModalLabel">Cadastrar Empresa</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{% url "register_employee" %}" method="post">{% csrf_token %}
          <div class="input-group mb-3">
            <span class="input-group-text">@</span>
            <div class="form-floating">
              <input type="text" class="form-control" id="id_enterprise" placeholder="Nome da empresa" name='enterprise'>
              <label for="id_enterprise">Nome da empresa</label>
            </div>
          </div>

          <div class="">
            <button type="submit" class="btn btn-outline-primary w-100">Cadastrar</button>
          </div>

        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal Setor -->
<div class="modal fade" id="setorModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="setorModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="setorModalLabel">Cadastrar Setor</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <form action="{% url "register_employee" %}" method="post">{% csrf_token %}
          <div class="input-group mb-3">
            <span class="input-group-text">@</span>
            <div class="form-floating">
              <input type="text" class="form-control" id="id_sector_name" placeholder="Setor" name='sector_name'>
              <label for="id_sector_name">Setor</label>
            </div>
          </div>

          <div class="input-group mb-3">
            <span class="input-group-text">@</span>
            <div class="form-floating">
              <input type="text" class="form-control" id="id_sector_phone" placeholder="Setor" name='sector_phone'>
              <label for="id_sector_phone">Ramal</label>
            </div>
          </div>

          <div class="">
            <button type="submit" class="btn btn-outline-primary w-100">Cadastrar</button>
          </div>

        </form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

records/templates/pages/epi/epi_create.html
{% extends "base.html" %}
{% block title %}EPIS{% endblock title %}

{% block content %}

{% if messages %}

  {% for msg in messages %}
    
    <div class="position-absolute z-3">
      <div class="alert alert-success text-align-center px-5" role="alert">
        {{ msg }}
      </div>
    </div>

  {% endfor %}

{% endif %}

<form action="{% url "register_epi" %}" method="post">{% csrf_token %}

<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-user-shield"></i></span>
    <div class="form-floating">
      {{form.name}}
      <label for="id_name">Nome EPI</label>
    </div>
</div>
    
<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-1"></i></span>
    <div class="form-floating">
      {{form.number}}
      <label for="id_number">Número/Tamanho</label>
    </div>
</div>

<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-box-open"></i></span>
    <div class="form-floating">
        {{form.amount}}
        <label for="id_amount">Quantidade</label>
    </div>
</div>

<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-clipboard-list"></i></span>
    <div class="form-floating">
        {{form.description}}
        <label for="id_description">Descrição</label>
    </div>
</div>

<div class="mb-3">
  <button type="submit" class="btn btn-outline-primary btn-lg w-100">Registrar <i class="fa-solid fa-check"></i></button>
</div>

</form>

{% endblock content %}

records/templates/pages/key/key_create.html
{% extends "base.html" %}
{% block title %}Key{% endblock title %}

{% block content %}

<form action="{% url "register_key" %}" method="post">{% csrf_token %}

<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-key"></i></span>
    <div class="form-floating">
      {{form.name}}
      <label for="id_name">Nome da chave</label>
    </div>
</div>
    
<div class="input-group mb-3">
    <span class="input-group-text"><i class="fa-solid fa-1"></i></span>
    <div class="form-floating">
      {{form.number}}
      <label for="id_number">Número</label>
    </div>
</div>

<div class="input-group mb-3">
  <span class="input-group-text"><i class="fa-solid fa-up-right-and-down-left-from-center"></i></span>
  <div class="form-floating">
    {{form.amount}}
    <label for="id_amount">Quantidade de cópia</label>
  </div>
</div>

<div class="mb-3">
  <button type="submit" class="btn btn-outline-primary btn-lg w-100">Registrar <i class="fa-solid fa-check"></i></button>
</div>

</form>

{% endblock content %}

records/templates/pages/login/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}

{% block content %}

    <h1>Login</h1>

{% endblock content %}

records/templates/pages/login/logout.html
{% extends "base.html" %}
{% block title %}Logout{% endblock title %}

{% block content %}

    <h1>Logout</h1>

{% endblock content %}

records/templates/pages/user/user_create.html
{% extends "base.html" %}
{% block title %}User{% endblock title %}

{% block content %}

    <h1>User</h1>

{% endblock content %}

records/templates/partials/_header.html
<div class="fixed-top">
    <ul class="nav nav-underline mx-5 p-2">
        <li class="nav-item">
            <button class="btn btn-outline-secondary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"><i class="fa-solid fa-bars"></i></button>
        </li>

        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "logout_view" %}"><span>{{ user.username }}</span></a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "login_view" %}">Login</a>
            </li>
        {% endif %}     

    </ul>
</div>

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasRightLabel">Sistema de cadastro empresarial</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    
    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
              Funcionários
            </button>
          </h2>
          <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">

                <div class="list-group">
                    <a href='{% url "register_employee" %}' type="button" class="list-group-item list-group-item-action">Cadastrar</a>
                    <a type="button" class="list-group-item list-group-item-action">Editar</a>
                    <a type="button" class="list-group-item list-group-item-action">Deletar</a>
                    <a type="button" class="list-group-item list-group-item-action">Exibir</a>
                </div>

            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
              Chaves
            </button>
          </h2>
          <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              
                <div class="list-group">
                    <a href='{% url "register_key" %}' type="button" class="list-group-item list-group-item-action">Cadastrar</a>
                    <a type="button" class="list-group-item list-group-item-action">Editar</a>
                    <a type="button" class="list-group-item list-group-item-action">Deletar</a>
                    <a type="button" class="list-group-item list-group-item-action">Exibir</a>
                </div>

            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
              EPI's
            </button>
          </h2>
          <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
              
                <div class="list-group">
                    <a href='{% url "register_epi" %}' type="button" class="list-group-item list-group-item-action">Cadastrar</a>
                    <a type="button" class="list-group-item list-group-item-action">Editar</a>
                    <a type="button" class="list-group-item list-group-item-action">Deletar</a>
                    <a type="button" class="list-group-item list-group-item-action">Exibir</a>
                </div>

            </div>
          </div>
        </div>
      </div>

  </div>
</div>